### ISSUE TITLE
PWA - markdown images are broken

### ISSUE THREAD

**Issue by cbarkerms** [Microsoft/InsiderDevTour18-Labs#19]

**Comment by fpelaez** [comment]
Fixed on commit https://github.com/MicrosoftDocs/labs-pr/commit/2c4c4cd4a1823a1828664aef5c34f891e22fa42e

**Comment by cbarkerms** [comment]
There are still broken links.  See Lab-part-7.md and https://review.docs.microsoft.com/en-us/labs/insiderdevtour2018/pwa/index?branch=insiderdevtour%2Fdev (under F12 tools) for examples.

**Comment by michael-hawker** [comment]
Part 6 as well: https://review.docs.microsoft.com/en-us/labs/insiderdevtour2018/pwa/index?branch=insiderdevtour%2Fdev&ocid=idt_labs_cta_web2lab_pwa&tutorial-step=6

**Comment by cbarkerms** [comment]
full list:

•	Line 0: [Warning] Invalid file link:(~/insiderdevtour2018/media/Picture62.PNG). 
•	Line 0: [Warning] Invalid file link:(~/insiderdevtour2018/media/Picture72.PNG). 
•	Line 0: [Warning] Invalid file link:(~/insiderdevtour2018/media/Picture52.PNG). 
•	Line 0: [Warning] Invalid file link:(~/insiderdevtour2018/media/Picture64.png). 
•	Line 0: [Warning] Invalid file link:(~/insiderdevtour2018/media/Picture60.PNG). 
•	Line 0: [Warning] Invalid file link:(~/insiderdevtour2018/media/Picture40.PNG). 
•	Line 0: [Warning] Invalid file link:(~/insiderdevtour2018/media/Picture22.jpeg). 
•	Line 0: [Warning] Invalid file link:(~/insiderdevtour2018/media/Picture57.PNG). 
•	Line 0: [Warning] Invalid file link:(~/insiderdevtour2018/media/Picture65.PNG). 
•	Line 0: [Warning] Invalid file link:(~/insiderdevtour2018/media/Picture55.PNG). 
•	Line 0: [Warning] Invalid file link:(~/insiderdevtour2018/media/Picture71.jpg). 
•	Line 0: [Warning] Invalid file link:(~/insiderdevtour2018/media/Picture39.PNG). 
•	Line 0: [Warning] Invalid file link:(~/insiderdevtour2018/media/Picture59.PNG). 
•	Line 0: [Warning] Invalid file link:(~/insiderdevtour2018/media/Picture59.PNG). 
•	Line 0: [Warning] Invalid file link:(~/insiderdevtour2018/media/Picture56.PNG). 
•	Line 0: [Warning] Invalid file link:(~/insiderdevtour2018/media/Picture74.PNG). 
•	Line 0: [Warning] Invalid file link:(~/insiderdevtour2018/media/Picture54.PNG). 
•	Line 0: [Warning] Invalid file link:(~/insiderdevtour2018/media/Picture63.PNG). 
•	Line 0: [Warning] Invalid file link:(~/insiderdevtour2018/media/Picture73.PNG). 
•	Line 0: [Warning] Invalid file link:(~/insiderdevtour2018/media/Picture53.PNG). 
•	Line 0: [Warning] Invalid file link:(~/insiderdevtour2018/media/Picture38.PNG). 
•	Line 0: [Warning] Invalid file link:(~/insiderdevtour2018/media/Picture58.PNG). 
•	Line 0: [Warning] Invalid file link:(~/insiderdevtour2018/media/Picture61.PNG). 
•	Line 0: [Warning] Invalid file link:(~/insiderdevtour2018/media/Picture41.PNG). 
•	Line 0: [Warning] Invalid file link:(~/insiderdevtour2018/media/Picture51.PNG).
